### ISSUE TITLE
withScalingFactor doesn't work if the fontSize is a Bytestring

### ISSUE THREAD

**Issue by querenker** [tom95/Pheno#50]
MessageNotUnderstood : Bytestring>>withScalingFactor

![screen shot 2018-06-20 at 11 25 39](https://user-images.githubusercontent.com/9405540/41649898-031d0ac2-747d-11e8-9823-67606214f4bb.png) #

**Comment by querenker** [comment]
This bug can for example be reproduced with `PHTagListExample open`

**Comment by ekrebs5** [comment]
loading with all dependencies per metacello leads to this:
![grafik](https://user-images.githubusercontent.com/12158488/41771087-43668192-7614-11e8-9e8c-b9c33cb5ff1f.png)

**Comment by tom95** [comment]
Are you sure you successfully loaded everything? could you take a screenshot of PHTextEntry>>updateText:?

**Comment by ekrebs5** [comment]
now pheno is definitely up-to-date on both our system

good news: works perfectly for me now

bad news: TagLists still error for Alex

**Comment by tom95** [comment]
I can't reproduce this locally. Could you run `PHBootstrapTheme new use` to ensure that you have a fresh copy of the theme?

**Comment by querenker** [comment]
Thank you! This fixed it indeed 👍
