### ISSUE TITLE
Infinite loop in changed/update

### ISSUE THREAD

**Issue by codeZeilen** [tom95/Pheno#55]
This occurred when loading the Morphic Tutorial project together with a Pheno project.

After a call to #openAsTool we ended up in Morph>>#addedMorph: (see below) during which setting the parent of a styleContext seems to trigger an infinite loop between changed and update calls.

```Smalltalk
Morph>>#addedMorph: aMorph

	aMorph styleContext parent: self styleContext.
	
	self updateHierarchyStyleState
```

**Comment by tom95** [comment]
Could you explain the intent of this method's last line?
```smalltalk
MotuPlayground>>#initialize

	super initialize.
	self frameFractions: (0@0 rect: 1@1).
	self setUpBackground.
	super addMorph: Project currentWorld
```
If removed, there's no more problems (and the first two lectures worked fine)

**Comment by codeZeilen** [comment]
Wat. That explains a lot. 

Sorry for not seeing this...
